#ifndef REDPITAYA_CONVERTERS_12_CONFIG_H
#define REDPITAYA_CONVERTERS_12_CONFIG_H

#define REG_REDPITAYA_CONVERTERS_12_CONF		0
#define REG_REDPITAYA_CONVERTERS_12_ADC_DAC_SEL        	1
#define REG_REDPITAYA_CONVERTERS_12_CONF_EN	    	2
#define REG_REDPITAYA_CONVERTERS_12_PLL_EN              3

/* reg input bit */
#define REDPITAYA_CONVERTERS_12_CONF_SW   	  (0x1 << 0)
#define REDPITAYA_CONVERTERS_12_CONF_HW  	  (0x2 << 0)
#define REDPITAYA_CONVERTERS_12_ADC_DAC_SEL_SW    (0x1 << 2)
#define REDPITAYA_CONVERTERS_12_ADC_DAC_SEL_HW    (0x2 << 2)
#define REDPITAYA_CONVERTERS_12_CONF_EN_SW        (0x1 << 4)
#define REDPITAYA_CONVERTERS_12_CONF_EN_HW        (0x2 << 4)
#define REDPITAYA_CONVERTERS_12_PLL_EN_SW  	  (0x1 << 6)
#define REDPITAYA_CONVERTERS_12_PLL_EN_HW         (0x2 << 6)

/* ioctl */
#define REDPITAYA_CONVERTERS_12_SET(__reg)_IOW('a', __reg, unsigned long)
#define REDPITAYA_CONVERTERS_12_GET(__reg)_IOR('a', __reg, unsigned long)

#endif /* REDPITAYA_CONVERTERS_12_CONFIG_H */
