#ifndef REDPITAYA_CONVERTERS_12_CONFIG_H
#define REDPITAYA_CONVERTERS_12_CONFIG_H

#define REG_REDPITAYA_CONVERTERS_12_CONF		0
#define REG_REDPITAYA_CONVERTERS_12_ADC_DAC_SEL        	1
#define REG_REDPITAYA_CONVERTERS_12_CONF_EN	    	2
#define REG_REDPITAYA_CONVERTERS_12_PLL_EN              3
#define REG_REDPITAYA_CONVERTERS_12_PLL_OK              4

/* ioctl */
#define REDPITAYA_CONVERTERS_12_SET(__reg) _IOW('a', __reg, unsigned long)
#define REDPITAYA_CONVERTERS_12_GET(__reg) _IOR('a', __reg, unsigned long)

#endif /* REDPITAYA_CONVERTERS_12_CONFIG_H */
